name: Build and Release MSI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore NuGet packages
        run: nuget restore src/ProjectShamsi.sln

      - name: Build ProjectShamsi
        run: msbuild src/ProjectShamsi.sln /p:Configuration=Release

      - name: Build Installer
        run: |
          mkdir artifact
          candle.exe -o artifact/ProjectShamsi.wixobj installer/Product.wxs -d"ProjectShamsi.TargetDir=src\ProjectShamsi\bin\Release\net48"
          light.exe -out artifact/ProjectShamsi.msi artifact/ProjectShamsi.wixobj

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProjectShamsi-Installer
          path: artifact/ProjectShamsi.msi
