name: Build ProjectShamsi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Install WiX Toolset
      run: choco install wixtoolset --yes

    - name: Restore NuGet packages
      run: dotnet restore src/ProjectShamsi.sln

    - name: Build Solution and Installer
      run: msbuild installer/ProjectShamsi.Setup/ProjectShamsi.Setup.wixproj /p:Configuration=Release

    - name: Upload MSI artifact
      uses: actions/upload-artifact@v4
      with:
        name: ProjectShamsi-Installer
        path: installer/ProjectShamsi.Setup/bin/Release/*.msi
