name: Build ProjectShamsi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Updated to v4 for best practice

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Install WiX Toolset
      run: choco install wixtoolset --yes

    # This is the new, required step
    - name: Restore NuGet packages
      run: dotnet restore src/ProjectShamsi.sln

    - name: Build Solution
      run: msbuild src/ProjectShamsi.sln /p:Configuration=Release

    # This is the new diagnostic step
     - name: List all files after build
       run: ls -R

    - name: Upload MSI artifact
      uses: actions/upload-artifact@v4
      with:
        name: ProjectShamsi-Installer
        path: src/ProjectShamsi.Setup/bin/Release/*.msi # Corrected the path to the MSI
